### ISSUE TITLE
Side profile not working on slow browser?

### ISSUE THREAD

**Issue by ryansit** [auduno/clmtrackr#115]
This isn't an issue, more of a question.  I am testing on the new iOS 11 beta, Safari.  On desktop Safari 11 and everywhere else everything works fine.  

On this slower iPhone setup it does this weird thing where it doesn't match side profiles at all.  It only matches up the straight front facing landmarks.  

The question is if this is normal?  Does the algorithm gracefully degrade to a more simple match if it is a slow device or something?  I want to try to fix it, but I don't see any parameters or code that makes it degrade on slow devices.  So I am wondering if it is a bug or works as expected.

**Comment by auduno** [comment]
Hmm, the only degradation clmtrackr does, is to switch to slower calculations if webgl is not supported, but webgl should be supported on Safari. It might be a a bug, but it's a bit hard for me to test since I don't have iOS 11 beta installed. 

Note that the face detection in clmtrackr is a bit limited, it strictly only is trained to detect frontal faces, so it might have a hard time detecting faces that are turned sideways.

**Comment by ryansit** [comment]
Yes webgl is running.  So basically it using just the stock face frame and positions and scales it.  It does not track eyebrows up/down, opening/closing mouth, head side to side.  It doesn't match or move the eyes/nose/month, just seems to use a default face starting template only and position and scale.  

Do you have a function or debugging suggestions for me to look at?  

The good news is it works on iOS 11 :)

This might be the same bug another person reported with the emotion detection not working.

**Comment by ryansit** [comment]
One quirk on iOS is in the <video> tag you need to add playsinline after loop so that it plays the video inline and not full screen.

Also, did you get my emails I sent you?  If so and you are not interested that is fine, just wanted to know.  Thank you!

**Comment by auduno** [comment]
Hmm, that sounds like an odd bug. Could you tell me a little bit more about the issue, does the tracking follow your face at all, or does it seem stuck in one place? And does this happen every time, or is it somewhat random? I've seen a related issue on Safari where canvas output returns only the first frame from a video (which might be due to [this safari bug](https://bugs.webkit.org/show_bug.cgi?id=153588)), but I'm not sure if it's related.

**Comment by ryansit** [comment]
Yes it follows the face around.  It happens every time.  

Apple just released the iOS11 Public Beta, which is pretty solid:
https://beta.apple.com/sp/betaprogram/

It is probably the best way to check it out, plus you can check the aspect ratio is working and get it fully working on iOS.  Like I mentioned before mobile Safari needs playsinline in the video tag, plus doing navigator.mediaDevices.enumerateDevices() to show and set the available cameras helps for both iOS and Android.  

Else let me know if you would like me to console.log anything, or we can wait a bit longer for later betas and see how it goes.

One additional thing to note, it works on Safari 11 desktop, but not Safari 11 iOS 11.  Weird...

Ryan

**Comment by auduno** [comment]
Yes, I might have to install iOS 11 to debug this properly. Do you see any errors in JavaScript console? And do you see this issue when running the examples, or is this your custom code?

**Comment by ryansit** [comment]
No errors in Javascript.  The examples don't work on iOS for a number of errors that I mentioned in other comments.  But my code isn't really customized, the root of it is very similar to the examples so it should work.  Thank you!

**Comment by auduno** [comment]
I finally took the leap and installed iOS11 beta. It turns out iOS WebGL implementation does not fully support OES_TEXTURE_FLOAT extension (even though it says it does), so the facial fitting fails. This is why you see the issue with the face model not properly tracking the face.

I'll try to work on a fix for this during the next week.

**Comment by ryansit** [comment]
You are the best!

**Comment by auduno** [comment]
I'v added a fix for this now in the dev branch, so the examples in dev should now work in iOS 11. Note that I have not been able to get the WebGL implementation working, since iOS WebGL does not support rendering to floating point textures, so currently it just falls back to doing calculations on CPU instead. Fortunately this seems to run pretty smoothly anyway, at least when I tried it on my iPhone 6!

**Comment by ryansit** [comment]
I have updated my code and confirmed this fix works.  Yeah clmtrackr works on all major browsers now.  iOS 11 should be final release this month.

**Comment by auduno** [comment]
Great to hear, thanks for the feedback!
