### ISSUE TITLE
The error "a patchresponse was monotone"

### ISSUE THREAD

**Issue by shinriyo** [auduno/clmtrackr#39]
Hello

I guess that the camera was dark or white.
The error occurred.

```a patchresponse was monotone, causing normalization to fail. Leaving it unchanged.```

And later.

```Uncaught TypeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': float parameter 1 is non-finite.```

sometimes the error happened.

when the error happened the camera can't detect later.

Could you tell me how to fix it?
Or is it bug of library?

**Comment by auduno** [comment]
Hi,
the first error message about monotone patch responses is nothing to worry about, it's just for information. The second bug sounds like you tried to get the image data from a canvas before the image was loaded, see http://stackoverflow.com/questions/25492304/exception-floating-parameter-is-not-finite-canvas

Not sure if that bug is in clmtrackr or in your code, I'd have to see the page to be able to tell.

**Comment by xesign** [comment]
Hello there. I tryed to make the 2 examples for clm.tracker of this video from Lauren McCarthy https://www.youtube.com/watch?v=1k3X4DLDHdc  

but didnt work. can anyone share an example made in P5.js for study.
