### ISSUE TITLE
freezes computer on ie9 - fast fourier transform is incredibly slow

### ISSUE THREAD

**Issue by verybigelephants** [auduno/clmtrackr#54]
i am well aware that ie9 is not one of the newest browsers but many people running windows 7 are still using it. however, i understand that this is probably not a priority for anyone so i realize that this may get just closed

anyways, when trying to init the clmtrackr model (for example, a model from the examples), the IE9 in about a minute or two, while other browsers do it in a couple of miliseconds

i have done some thorough benchmarking and it seems that the problems lies when doing the 2d fast fourier transforms. 

[this is the bottleneck](https://github.com/auduno/clmtrackr/blob/dev/clmtrackr.js#L2775)

the very root of the slow performance lies when the FFT.real_fft2d is being performed and fft1d called within it. it lasts for a couple of miliseconds but adds up **massively**, since it's done in a loop. google chrome, for example does it within 1/2 miliseconds

perhaps it would work with another FFT implementation faster on IE9? 

note: in order to make the library work on IE9 you need to include a TypedArray from somewhere, like from [here](http://inexorabletash.github.io/polyfill/typedarray.js)

**Comment by auduno** [comment]
There's not really a way to make it run fast on IE9 that I can think of. The reason IE9 is so slow, is because it doesn't natively support typed arrays, which speed up the fft calculations. I doubt there are any other fft implementations that are faster, since I was looking around for the fastest version I could find, and additionally optimized it even more to get it to run fast. 

Unfortunately, I think the best option for windows 7 users is to install another browser :(

**Comment by verybigelephants** [comment]
thank you for the answer! since i now know that the very root of the problem lies within TypedArrays now i know i can stop trying  :)
