### ISSUE TITLE
Need to detect hair and replace it by other custom hair.

### ISSUE THREAD

**Issue by chandu89** [auduno/clmtrackr#55]
Hi Auduno,
  First of all i want to say thank you that you build such a incredible JS.
Your JS is actually give position of Eyes, Lips, Nose but not Hair And how i can replace the hair with exact mapping point by other custom Hairs?
Please help me if possible.

**Comment by verybigelephants** [comment]
isn't hair on top of the head? anyways, if you need to trace the hair itself. like, the outline of the hair, you can see that the paper deals with facial features, not hair tracking http://dl.acm.org/citation.cfm?id=1938021

**Comment by chandu89** [comment]
@verybigelephants  thank for the suggestion but i am looking for built in Model.
So if you can help pls let me know.
And you have any other library Which can detect and replace that part of hair with custom hair

**Comment by auduno** [comment]
Hi, if you want to track hair as well, you'd have to use another model that tracks the hair as well. I don't have such a model, so you'd have to train it yourself. However, I'm not sure if the method used by clmtrackr works so well for tracking hair, since the size and style of hair differs a lot between persons. 

Actually I think what you might need to get good results of outlines of hair is probably image segmentation via convolutional networks, take a look at an example of it [here](http://www.eraseimage.com/).
