### ISSUE TITLE
batch mode

### ISSUE THREAD

**Issue by az0** [auduno/clmtrackr#64]
Is this library designed, or easily adapted, to run in offline/batch mode, such as to estimate emotions in 10,000 images stored locally?

**Comment by az0** [comment]
Hmm, seems easier to build it in Python by starting with this code 

https://github.com/auduno/clmtools/blob/master/pdm_builder/create_classifier.py

**Comment by auduno** [comment]
The library wasn't designed to do it, but it should be possible to do just by modifying the code in the [emotiondetection example ](http://auduno.github.io/clmtrackr/examples/clm_emotiondetection.html) and the [image tracking example](http://auduno.github.io/clmtrackr/clm_image.html), e.g. just adding a loop over several files which fit a face model and then classify the emotions. Note that you will have to run this in a webpage, as I haven't yet ported clmtrackr to node.js.

You're going to have problems using the clmtools code for this, since it was just made for training the models, not for running them.

**Comment by az0** [comment]
Thank you for the quick reply. 

I assume I can adapt clmtools to pickle the model in Python format instead of saving it in JavaScript. Then I can preprocess each image the same way it does for training, but then apply the pretrained model to it to score it.

If that doesn't work, I would consider running it in a web page.

**Comment by auduno** [comment]
You can run the emotion classification in python, but for preprocessing the images I used for training, I manually annotated the points of the faces, so there's no python script to do that :/
